#!/bin/bash

cd "$(dirname "$0")"
import_bin="$(realpath import-license.js)"

mkdir -p cache
cd cache

git clone https://github.com/spdx/license-list-data || true
cd license-list-data/json/details

node "$import_bin"
